name = input("enter name")
print(" you start in a dark room and suddenly the lights turn on, then you saw a shadow, he introdused himeself as diddy")
print(f" Diddy: hello there {name}...")
print("You: H...how do you know my name!")
print("Diddy: I KNOW EVERYTHING...")
[print("{PORTAL APPEARS}")
print("You: (gasp)!")
print(YOU HAVE NOW ENETERED THE DUNGEON)