name = input("enter name")
print(" you start in a dark room and suddenly the lights turn on, then you saw a shadow, he introdused himeself as diddy")
print(f" Diddy: hello there {name}...")
print("You: H...how do you know my name!")
print("Diddy: I KNOW EVERYTHING...")
[print("{PORTAL APPEARS}")
print("You: (gasp)!")
print("YOU HAVE NOW ENETERED THE DUNGEON")
print("...")
print("...")
print("RUMBLE...RUMBLE...")
print("YOU HAVE ENTERED THE FIRST DOOR")
print("...")
print("YOU SEE A GIANT SLEEPING SPIDER STANDING IN FRONT OF YOU")
print("YOU SEE A SWORD ON THE WALL")
print("YOU GRAB THE SWORD, HOPING THE SPIDER WAKES UP")
print("Spider:...")
print("Spider:..GRAGGGGHHHHHH!")
print("you have entered a fight scene")
choice = input("what would you like to do (Back Kick, Stab, Slash, Dance)")
    if choice = Back Kick
    print("THE SPIDER AVOIDS YOUR ATTACK, IT POUNCES AT YOU.")
    choice2 = input("what would you like to do (Dodge, Counter Punch, Stick Your Sword Out And Let The Spider Kill Itself )")
        if choice2 = dodge
        print("YOU TRY TO DODGE THE SPIDER, BUT IT BITES YOU BEFORE YOU GET TO MOVE...")
        print("YOU DIED")
        elif choice2 = Counter Punch 
        print("THE SPIDER BITES YOU HAND AS YOU TRY TO PUNCH IT")
        print("YOU DIED")
        elif choice2 = Stick Your Sword Out And Let The Spider Kill Itself
        print("YOU STICK OUT YOUR BLADE, AND THE SPIDER RUNS RIGHT INTO IT")
        print("YOU HAVE DEFEATED THE FIRST OF MANY BOSSES")
    elif choice = Stab
    print("YOUR QUICK ATTACK CATCHES THE SPIDER BY SUPRISE")
    print("YOU EASILY KILL THE SPIDER AS THE SWORD GOES THROUGH ITS BODY")
    print("YOU HAVE DEFEATED THE FIRST OF MANY BOSSES")
    elif choice = Slash
    print("YOUR ATTACK MAY BE STRONG, BUT ITS SLOW, LEAVING THE SPIDER PLENTY OF TIME TO DODGE AND MAKE AN ATTACK OF ITS OWN")
    print("THE SPIDER CATCHES YOU OFF GUARD AND BITES YOU, LEAVING YOU DEAD ON THE GROUND")
    print("YOU DIED")
    elif choice = Dance
    print("YOUR STUPIDITY HAS ROTTED THE SPIDERS BRAIN")
    print("YOU QUICKLY STAB THE SPIDER, AND IT DIES ON THE SPOT")
    print("YOU HAVE DEFEATED THE FIRST OF MANY BOSSES")